---
last_check:
  etag: '"9ec22bbaab9cb7e527e692cc85e46bbd"'
  version: 1.8.9
  at: 1540364787
checked_completion: true
completion_version: 1.8.9
endpoints:
  https://api.travis-ci.org/:
    access_token: y6P3hAE30WaEOdBk6TQ4JA
